"""Bundle source sections into a MaixVision single-file entry (no local imports)."""
from pathlib import Path
import ast

APP = Path(__file__).resolve().parents[1]
SECTIONS = ("config", "thermal", "calibration", "fusion", "hot_tracker", "rtsp_jpeg", "pipeline", "runtime")

def main():
    chunks = [
        '# MaixCAM2 + Thermal160 + YOLO fusion, standalone MaixVision entry.\n',
        '# Generated by tools/build_fusion_app.py. CONFIG below is editable for board use.\n',
        '# Source protocol attribution: see THIRD_PARTY.md. No sibling Python files required.\n',
    ]
    for section in SECTIONS:
        code = (APP / "src" / (section + ".py")).read_text(encoding="utf-8")
        chunks.append('\n# ---- ' + section + ' ----\n' + code + '\n')
    bundle = ''.join(chunks).rstrip() + '\n'
    ast.parse(bundle)
    (APP / "main.py").write_text(bundle, encoding="utf-8")
    print(f"Built {APP / 'main.py'} ({len(bundle.splitlines())} lines)")

if __name__ == '__main__':
    main()
